FORMAT: 1A
HOST: http://www.google.com

# Alfa

API to test parameters

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes?id={id}&testingGroup={testtingGroup}&collection={collection}]

+ Parameters

    + id = `1` (number, required) ... An unique identifier of the message
    
    + testingGroup = `testing` (optional) ... We have added the query URI template parameter - `limit`. This parameter is used for limiting the number of results returned by some actions on this resource. It does not affect every possible action of this resource therefore we will discuss it only at the particular action level below.
        + values 
            + `testing`
            + `staging`
            + `live`
            + `deploy`
            + `circleci`
            + `travisci`            
    
    + collection (string or something different as Instance Collection Object Class, `notes`) ... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt laoreet dui vitae faucibus.

### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
